#!/usr/bin/env node
/**
 * npm run build:web    -> dist/        the real website
 * npm run build:demo   -> dist-demo/   the sample-shop demo
 *
 * Exports the site, then makes it work on an ordinary static host.
 *
 * Expo pre-renders one HTML file per route, but a route with a parameter
 * (product/[id]) has no file for /product/abc123, so opening a shared
 * product link would 404. This adds a rewrite so any /product/<id> is
 * served the product page shell, which then loads the right piece.
 * The `_redirects` file is understood by Netlify and Cloudflare Pages.
 */
const { spawnSync } = require("node:child_process");
const fs = require("node:fs");
const path = require("node:path");

const demo = process.argv.includes("--demo");
const root = path.resolve(__dirname, "..");
const outName = demo ? "dist-demo" : "dist";
const out = path.join(root, outName);

// --clear: never let a cached demo bundle leak into a real build, or the
// reverse. SSJ_DEMO is forced either way so a stray shell variable can't
// flip the mode.
const result = spawnSync(`npx expo export --platform web --output-dir ${outName} --clear`, {
  cwd: root,
  stdio: "inherit",
  shell: true,
  env: { ...process.env, SSJ_DEMO: demo ? "1" : "" },
});
if (result.status !== 0) process.exit(result.status ?? 1);

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const full = path.join(dir, entry.name);
    return entry.isDirectory() ? walk(full) : [full];
  });
}

const rules = [];
for (const file of walk(out)) {
  const name = path.basename(file);
  if (!/^\[[^\]]+\]\.html$/.test(name)) continue;

  const dir = path.relative(out, path.dirname(file)).split(path.sep).join("/");
  if (!dir) continue;

  // A bracket-free copy: brackets in a rewrite target are not reliably
  // handled by every host.
  const shell = "_route.html";
  fs.copyFileSync(file, path.join(path.dirname(file), shell));
  rules.push(`/${dir}/*    /${dir}/${shell}    200`);
}

// Most specific directories first, so /admin/product/* wins over /product/*.
rules.sort((a, b) => b.split("/").length - a.split("/").length);

fs.writeFileSync(
  path.join(out, "_redirects"),
  [
    "# Generated by scripts/build-web.js -- serve parameterised pages from their shell.",
    "# Real files (e.g. /policy/privacy) are served directly and are not affected.",
    ...rules,
    "",
  ].join("\n"),
);

// Netlify, Cloudflare Pages and GitHub Pages all look for 404.html.
const notFound = path.join(out, "+not-found.html");
if (fs.existsSync(notFound)) fs.copyFileSync(notFound, path.join(out, "404.html"));

console.log(`\n${demo ? "Demo" : "Website"} ready in ${outName}/`);
for (const rule of rules) console.log(`  rewrite ${rule.replace(/\s+/g, " ")}`);
